### ISSUE TITLE
[1.18] ceramic shears cannot harvest glow lichen

### ISSUE THREAD

**Issue by esotericist** [cech12/BrickShears#11]
tested with ceramic shears 1.18-1.5.0.1 on forge 39.0.10 (although i also experienced this on 38.0.*)

glow lichen is meant to be harvested with shears, and unless you're intentionally having the ceramic shears be unable to collect certain materials, they should probably work here as well.

**Comment by cech12** [comment]
Thanks for your report! I will check that :)

**Comment by cech12** [comment]
I opened a PR to MinecraftForge to fix that issue: https://github.com/MinecraftForge/MinecraftForge/pull/8371

**Comment by esotericist** [comment]
oh, it's a forge issue? I didn't anticipate that

**Comment by cech12** [comment]
Yes, Vanilla hard coded the loot tables to vanilla shears. Forge edits the loot tables of every block with vanilla shears to use the shears tool action instead. But the Glow Lichen loot table is a bit different to the others and is not supported until the PR is merged. So every shears mod should have this issue actually ^^

**Comment by esotericist** [comment]
![image](https://user-images.githubusercontent.com/1569754/148708595-812dda02-1a2f-47e1-84e3-c1cf8712efda.png)

forge merged your PR, and now all is well on the glow lichen + ceramic shears front, provided one is playing 39.0.16.

yay! \o/

**Comment by cech12** [comment]
Nice to hear that! I will update the mod to use this Forge version :)
