### ISSUE TITLE
Ceramic Shears make bees hostile

### ISSUE THREAD

**Issue by Dekamir** [cech12/BrickShears#12]
Title self explanatory.
Vanilla shears don't.

**Comment by cech12** [comment]
Thanks for your report.

I am assuming that you placed a campfire under the beehive.

I will look into that :)

**Comment by cech12** [comment]
Which versions are you using? (Minecraft, Forge, Ceramic Shears)

**Comment by cech12** [comment]
For me everything works fine in the actual version:

Minecraft 1.18.1
Forge: 39.0.75
Ceramic Shears: 1.18.1-1.5.1.0

When a campfire is placed below the Beehive/Beenest, the bees do not become hostile, when it is sheared with Ceramic Shears or vanilla shears. When no campfire is placed, they become hostile.
https://minecraft.fandom.com/wiki/Bee#Attacking

Please provide more specific information.

**Comment by Dekamir** [comment]
_I opened this issue after reproducing the issue 3 times, but..._
I restarted the server and **now it works fine.** Maybe the trapdoors (blocking the smoke) were desynced. Sorry for the inconvenience!

**Comment by cech12** [comment]
Thanks for your answer :)
