### ISSUE TITLE
[Bug]: Failed to Create new World or Entering Existing World with the ceramicshears-fabric-1.21-3.2.0.0.jar installed

### ISSUE THREAD

**Issue by ayrus02** [cech12/BrickShears#28]
### Minecraft Version

1.21

### Mod Loader

Fabric

### Mod Loader Version

0.15.11 - 0.100.7+1.21

### Mod Version

ceramicshears-fabric-1.21-3.2.0.0.jar

### Modpack or other Mod

	- accessories 1.0.0-beta.6+1.21
	   |-- io_wispforest_endec 0.1.3
	   |-- io_wispforest_endec_gson 0.1.2
	   \-- io_wispforest_endec_netty 0.1.2
	- additionalstructures 5.0.0-fabric
	- advanced-xray-fabric 21.0.0
	- advancedbackups 3.6
	- alllootdrops 3.3
	- anvilrestoration 2.2
	- appleskin 3.0.2+mc1.21
	- architectury 13.0.4
	- areas 5.9
	- autofish 1.2.0-fabric-1.21
	- bambooeverything 21.0.2+mc1.21
	- betterspawnercontrol 4.5
	- biggerspongeabsorptionradius 3.5
	- biomesoplenty 21.0.0.11
	- bottleyourxp 3.3
	- bouncierbeds 2.3
	- brickfurnace 1.21-4.1.0.0
	- brickhopper 1.21-3.1.0.0
	- bucketlib 1.21-4.1.0.0
	- cardinal-components 6.1.0
	   |-- cardinal-components-base 6.1.0
	   |-- cardinal-components-block 6.1.0
	   |-- cardinal-components-chunk 6.1.0
	   |-- cardinal-components-entity 6.1.0
	   |-- cardinal-components-item 6.1.0
	   |-- cardinal-components-level 6.1.0
	   |-- cardinal-components-scoreboard 6.1.0
	   \-- cardinal-components-world 6.1.0
	- catalogue 1.10.1
	- ceramicbucket 1.21-6.1.0.0
	- ceramicshears 1.21-3.2.0.0
	- cloth-config 15.0.127
	   \-- cloth-basic-math 0.6.1
	- clumps 18.0.0.1
	- collective 7.71
	- configurabledespawntimer 4.1
	- configured 2.5.0
	- copperhopper 0.9.3+1.21
	- cryingghasts 3.4
	- dailydad 2.0.0
	- deathbackup 3.3
	- dismountentity 3.3
	- doubledoors 5.8
	- ender_pack 2.0.2
	- expcounter 1.21-0-fabric
	- extendedbonemeal 3.4
	- extractpoison 3.3
	- extrainv 1.0.4
	- fabric-api 0.100.7+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.67+b5597344d1
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bcd1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.15+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.18+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.4.2+c111832ad1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.25+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.12+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.10+e633f883d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.3+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1
	   |-- fabric-loot-api-v2 3.0.13+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.1+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.0+ab7edbacd1
	   |-- fabric-object-builder-api-v1 15.1.13+d1321076d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.10+65089712d1
	   |-- fabric-registry-sync-v0 5.0.25+5bd9f1bcd1
	   |-- fabric-renderer-api-v1 3.3.0+0ae0b97dd1
	   |-- fabric-renderer-indigo 1.6.5+48fb1586d1
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.71+df3654b3d1
	   |-- fabric-rendering-v1 5.0.5+df16efd0d1
	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f344d1
	   |-- fabric-resource-loader-v0 1.2.0+7e687b32d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.82+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.15+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8cd1
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- fleshz 1.5.1
	- framework 0.9.0
	   |-- com_electronwill_night-config_core 3.7.1
	   |-- com_electronwill_night-config_toml 3.7.1
	   |-- org_javassist_javassist 3.29.2-GA
	   \-- org_reflections_reflections 0.10.2
	- ftbessentials 2100.1.0
	- ftblibrary 2100.1.2
	- ftbultimine 2100.1.0
	- furnacerecycle 2.4
	- glitchcore 2.0.0.2
	   \-- net_jodah_typetools 0.6.3
	- goldenhopper 1.5.3
	- grassseeds 3.2
	- grindstonesharpertools 3.6
	- healingcampfire 6.0
	- healingsoup 4.9
	- hoetweaks 3.4
	- improvedsignediting 1.3
	- infinitetrading 4.4
	- inventoryhud ${version}
	- jade 15.1.4+fabric
	- java 21
	- jei 19.5.0.33
	- justenoughbreeding 1.2.4
	- keepmysoiltilled 2.3
	- kelpfertilizer 3.2
	- mcwbridges 3.0.0
	- mcwdoors 1.1.1
	- mcwfences 1.1.2
	- mcwholidays 1.1.0
	- mcwlights 1.1.1
	- mcwtrpdoors 1.1.3
	- menulogue 1.21-1.0.6
	- midnightlib 1.5.7
	- minecraft 1.21
	- mineralchance 3.6
	- monolib 1.3.0
	- more_beautiful_torches 3.0.0
	- morezombievillagers 3.5
	- mousetweaks 2.26
	- moveboats 3.3
	- moveminecarts 3.5
	- mr_smelting_plus 1.0.7
	- nametagtweaks 3.6
	- nofeathertrample 1.2
	- owo 0.12.10+1.21
	   \-- io_wispforest_endec_jankson 0.1.0
	- passiveshield 3.5
	- placeableblazerods 3.5
	- randombonemealflowers 4.5
	- randomore 1.3.0
	- randomvillagenames 3.6
	- realisticbees 3.9
	- replantingcrops 5.3
	- repurposed_structures 7.5.3+1.21-fabric
	- resource_backpacks 0.6.1-BETA
	- resourceconfigapi 1.21-2.0.0
	- resourcelibrary 1.21-2.0.2
	- scaffoldingdropsnearby 3.2
	- simple_backpack 1.6.8
	   \-- blue_endless_jankson 1.2.3
	- snowballsfreezemobs 3.6
	- softerhaybales 3.2
	- spidersproducewebs 3.4
	- stackrefill 4.4
	- terrablender 4.0.0.1
	- toms_storage 2.0.6
	   |-- cardinal-components-base 6.1.0
	   \-- cardinal-components-block 6.1.0
	- travelersbackpack fabric-1.21-10.0.4
	- treeharvester 8.9
	- villagebellrecipe 3.5
	- villagerdeathmessages 3.4
	- villagernames 8.0
	- welcomemessage 2.5
	- woodenhopper 1.21-3.1.0.0
	- xaerominimap 24.2.1
	- xaeroworldmap 1.38.8
	- youritemsaresafe 4.4
	- zombievillagersfromspawner 3.8

### Describe the Issue

Failed to Create new World or Entering Existing World with the ceramicshears-fabric-1.21-3.2.0.0.jar installed.

![image](https://github.com/user-attachments/assets/5ee73abb-5b45-459a-9cf0-10692a102232)

### Logs

https://pastebin.com/GEtZuU6F

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by cech12** [comment]
Thanks for your report! I will look into that, when I have time :)
As a workaround for now, you could downgrade your Fabric version to (example: 0.15.11 - 0.100.3+1.21)

**Comment by ayrus02** [comment]
> Thanks for your report! I will look into that, when I have time :) As a workaround for now, you could downgrade your Fabric version to (example: 0.15.11 - 0.100.3+1.21)

Hi @cech12,

I've try to downgrade the Fabric version to 0.15.11 - 0.100.3+1.21, and the problem are still exists, I cannot create new world or open existing world with the CeramicShears enabled.

Below are the log after I downgraded to Fabric version to 0.15.11 - 0.100.3+1.21,

https://pastebin.com/D93HWztR

Regards,
ayrus02

**Comment by cech12** [comment]
That's weird. That is the version I do all my tests. Thanks for your response. I will look into that :)

**Comment by cech12** [comment]
Thanks again for your report! Unfortunately, I  could not reproduce the error, but I have an idea what caused the issue in your mod pack. I hope I could fix it in the upcoming version 1.21-3.2.0.1. If not, feel free to re-open the issue.
Please let me know, if the update works for you. :)

**Comment by ayrus02** [comment]
Hi @cech12, 

With the updated version 1.21-3.2.0.1, I can confirm that the CeramicShears and WoodenShears can now once again be loaded and used successfully on my game, I've tried it in SinglePlayer mode and Multiplayer Server/Client mode.
Thanks again for your time developing and bug-fixing the mods. 

![image](https://github.com/user-attachments/assets/86cae510-46e6-4928-90ca-6f6594074b38)

Regards,
ayrus02

**Comment by cech12** [comment]
Nice to hear that! Thanks for your feedback! 😁
