### ISSUE TITLE
Ceramic Shear cause Simple Farming Mod seed not drop from breaking grass

### ISSUE THREAD

**Issue by kokjoo89** [cech12/BrickShears#3]
MC Version: 1.15.2
Forge Version: 31.1.37
Ceramic Shear Version: 1.1.0-1.15.1+
Simple Farming Version: 1.15.2-1.2.7

I tried clean install with simple farming and Ceramic shear. It only work without ceramic shear installed. No idea how and why...

**Comment by cech12** [comment]
Hey thanks for this issue! That is maybe a bug of Ceramic Shears which can cause the incompatibility, I think. I will look at this and fix this in the next version.

**Comment by cech12** [comment]
Fixed!

upcoming known bug: breaking with ceramic shears also generate other drops (like seed at grass) 

(will be fixed when forge:shears tag is added to forge)
https://github.com/MinecraftForge/MinecraftForge/pull/6540
https://github.com/MinecraftForge/MinecraftForge/pull/6539

**Comment by cech12** [comment]
Released in 1.2.0
