### ISSUE TITLE
[Crash] Crash when trying to dispenser with ceramic shears on beehives.

### ISSUE THREAD

**Issue by Bernasss12** [cech12/BrickShears#9]
Mod version: 1.3.2
Forge version: 1.16.4-35.1.37
I am currently playing with the mod on the Sky Bees modpack other players playing the same pack have confirmed the behavior.

The way to reproduce the crash is:
Set up a dispenser facing an apiary with ceramic shears in it and then power it with redstone and it will instantly crash the game.

Here is the crash log:
https://paste.ee/p/aqB2P

If you need anything else don't mind asking :)

**Comment by cech12** [comment]
Thanks for your report. The version 1.4.0 will fix this issue.
